### ISSUE TITLE
Can I use A Qlogic qle2560？

### ISSUE THREAD

**Issue by LurenAA** [benjojo/IPoverFC#1]
Hello，I have seen your blog。It is great。I wonder can I use Qlogic qle2560？ I saw the SCST driver is for qla25xx， is “qle” qual to “qla” ？I saw that the card on the picture of README is a Qlogic qla2562.
I am a rookie. thank you.

**Comment by benjojo** [comment]
This is more of a question to the SCST project rather than this, Since it
just uses SCST to transfer the data on the target and. And raw SCSI on the
other.

**Comment by LurenAA** [comment]
Thank you
